### PR TITLE
Fix casting to GitLabMergeRequestTrigger and add more debug logs in Jenkins for plugin. Add option to alwaysIgnoreMRWorkInProgress

### PR DESCRIPTION
**Pull request by mifitous**
Fixing [#148](https://github.com/jenkinsci/gitlab-branch-source-plugin/issues/148)

Added support to https://github.com/jenkinsci/gitlab-branch-source-plugin/issues/148#issuecomment-957286005 
alwaysIgnoreMRWorkInProgress
image

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by mifitous** [comment]
@jetersen : fixed the classname in GitLabWebHookListener.java#43 to GitLabMergeRequestTrigger
without that, https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/252 is not working
Kindly review and merge please?
Thank you !

**Comment by mifitous** [comment]
Hi @jetersen 
Can you please review and approve this one?
Thank you !

**Comment by mifitous** [comment]
@jetersen?
Thank you !

**Comment by mifitous** [comment]
> @jetersen? Thank you !

**Review by jetersen — APPROVED** [review]
LGTM, would you mind making the PR title more respective of the changes?

**Comment by mifitous** [comment]
> LGTM, would you mind making the PR title more respective of the changes?

done

**Comment by mifitous** [comment]
Thanks a lot @jetersen

**Pull request merged**
