### PR TITLE
use the group avatar as default if project does not have an avatar

### PR DESCRIPTION
**Pull request by casz**
Yet another nice user experience improvement!

### CODE REVIEW

**Comment by baymac** [comment]
I am 50-50 with this feature. I doubt it might create confusion for some users who have avatars for some projects.

**Comment by casz** [comment]
This is lifted from Argelbargel's version 😓

**Comment by baymac** [comment]
So if you are using a user, all the projects will have user profile pic?

**Comment by casz** [comment]
If the project does not have an avatar yes.

We could limit it to groups 😓

**Comment by baymac** [comment]
@casz Tbh, I am more inclined towards not including this feature. Although I think we better ask for user feedbacks on this. What do you say?

**Comment by baymac** [comment]
I am closing this pr for now.

**Comment by casz** [comment]
😭 What if I make it a trait?

**Comment by baymac** [comment]
I think that is a nice idea. I think we can add a trait for GitLab Avatar
(like a generic one) and add options to it in future. For now it can have
only one option.

**Pull request closed without merging**
