### PR TITLE
Replace PNG icons with SVGs

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed exchanges the PNG icons with SVG icons, to integrate better with the modern appearance of Jenkins:

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by NotMyFault** [comment]
Heyo @LinuxSuRen,
do you mind taking a look? Would be nice to have this one available as well on the next LTS, which focuses a lot on UI improvements.
Thanks in advance!

**Review by jetersen — APPROVED** [review]

**Comment by jetersen** [comment]
@NotMyFault should the jenkins version be bumped?

**Comment by NotMyFault** [comment]
> @NotMyFault should the jenkins version be bumped?

If you want to, though this works even on an older baseline.

**Comment by jetersen** [comment]
Thanks @NotMyFault all I wanted to know 😄

**Pull request merged**
