### PR TITLE
Impl GitLabAvatarTrait

### PR DESCRIPTION
**Pull request by baymac**
Based on https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/45#issuecomment-528282373. Kindly approve the pr asap as we have a new release today.

### CODE REVIEW

**Comment by baymac** [comment]
@ChristianCiach

**Comment by ChristianCiach** [comment]
LGTM.

Usually I try to avoid negated logic in fields and methods like `doDisableProjectAvatar()` and would call it `useProjectAvatar()` instead. But I guess it makes sense in the context of this "Disable-something"-trait.

**Comment by baymac** [comment]
I agree with you on the negative logic part but we have other disable traits and it is consistent with that so implemented this way.

**Comment by baymac** [comment]
@casz I agree with you but for the time being this can be a temporary fix.

**Pull request merged**
