### PR TITLE
release drafter ooopsie :man_facepalming:

### PR DESCRIPTION
**Pull request by casz**

### CODE REVIEW

**Comment by casz** [comment]
Good catch @baymac

**Comment by baymac** [comment]
@casz Should we maintain a changelog like GitHub Branch Source Plugin? https://wiki.jenkins.io/display/JENKINS/GitHub+Branch+Source+Plugin or do you have any better way to do it?

**Comment by casz** [comment]
The changelog is on GitHub releases.
Drafter will help draft it
See https://github.com/jenkinsci/configuration-as-code-plugin/releases for awesomeness!

**Comment by baymac** [comment]
Alrighty :+1:

**Comment by casz** [comment]
There is ongoing work to have https://plugins.jenkins.io to pull data from GitHub 
We recently prepared for this on JCasC
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1004

See PR and JIRA for ongoing work!
https://github.com/jenkins-infra/plugin-site-api/pull/54
https://issues.jenkins-ci.org/browse/WEBSITE-406?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel

**Comment by baymac** [comment]
> There is ongoing work to have https://plugins.jenkins.io to pull data from GitHub
> We recently prepared for this on JCasC
> [jenkinsci/configuration-as-code-plugin#1004](https://github.com/jenkinsci/configuration-as-code-plugin/pull/1004)
> 
> See PR and JIRA for ongoing work!
> [jenkins-infra/plugin-site-api#54](https://github.com/jenkins-infra/plugin-site-api/pull/54)
> https://issues.jenkins-ci.org/browse/WEBSITE-406?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel

Will surely be a help for our plugin.

**Pull request merged**
