### PR TITLE
JENKINS-58525 Fixed job based pipeline reporting

### PR DESCRIPTION
**Pull request by baymac**
Previously, Pipeline `name` was set to Job Name if same status is reported by different Jobs it created multiple stages. After the changes the pipeline status looks like this:

Screenshot from 2019-07-17 12-10-47

Screenshot from 2019-07-17 12-13-59

Multiple entries is not created as the job names are now inside the `description` of pipeline.

Pipeline = GitLab Pipeline
Job = Jenkins Job

### CODE REVIEW

**Comment by baymac** [comment]
Requesting review from @jenkinsci/gsoc2019-gitlab-multibranch-pipeline

**Comment by casz** [comment]
Hmmm, perhaps it would be a good idea to check what happens with multiple builds done on same commit sha and the same build name.
We noticed that Argelbargel's version did not update the latest build status correctly basically blocking a pull request until a new commit sha was added.

We use GitVersion which updates the Jenkins build's display name.

image
The build that is red is the one that was reported even though never builds were built that turned green.

**Comment by baymac** [comment]
@casz It doesn't matter if the build name is the same because the pipeline name is not based on build/job name anymore. The pipeline names are based on heads which makes it only possiblity `jenkinsci/branch`,  `jenkinsci/mr` and  `jenkinsci/tag`. So if the build fails in one attempt or say gets canceled and the build passes in the next attempt then the pipeline status is `SUCCESS` because the latest build status overrides the previous build status.

**Comment by casz** [comment]
Cool 😅 Just don't want the carry over the odd logic from previous attempts 🤣

**Comment by casz** [comment]
Hmm, I still think we can get into an odd scenario here @baymac

Project is configured to build PRs and merge with the target branch.

let's say I have a PR targeting `master`, and the build goes green.
Then someone else takes my same commit/branch and targets `release/1.1.1`
They now have a green build which they are free to merge into `release/1.1.1` without CI build that would result in build failure due to some missing updates to the project files that are merged to master but not into `release/1.1.1`

**Comment by baymac** [comment]
> Hmmm, perhaps it would be a good idea to check what happens with multiple builds done on same commit sha and the same build name.
> We noticed that Argelbargel's version did not update the latest build status correctly basically blocking a pull request until a new commit sha was added.
> 
> We use GitVersion which updates the Jenkins build's display name.
> 
> image
> The build that is red is the one that was reported even though newer builds were built that turned green.

I get what you are trying to say. Is it the same thing you mentioned ^here? Or is it different case?

**Comment by casz** [comment]
these are two different cases :)

**Comment by baymac** [comment]
> Hmm, I still think we can get into an odd scenario here @baymac
> 
> Project is configured to build PRs and merge with the target branch.
> 
> let's say I have a PR targeting `master`, and the build goes green.
> Then someone else takes my same commit/branch and targets `release/1.1.1` in a new PR.
> They now have a green build which they are free to merge into `release/1.1.1` without CI build that would result in build failure due to some missing updates to the project files that are merged to master but not into `release/1.1.1`

In the current impl, there will be one status type (e.g. jenkinsci/mr, jenkinsci/tag etc.) for one commit. Since the pipeline status is based on a commit, it will fail if first pr passed and second pr failed. The second failure will override the first pass.

To fix this even if we somehow give different names(say job names) to both pr statuses, pipeline status will show `failed` is only one of the pr fails. This is because GitLab interprets pipeline status as pipeline stages. So for GitLab it is like failing a stage so it is a overall failure. This can only be fixed by the user. In order to merge the first pr, you need to rebuild the pipeline in Jenkins.

For example, if the builds have different name. Say MR-20 and MR-21 originates from `feature/pipeline-status` and targets `develop` and `master` respectively. And MR-21 build passed and MR-20 build is canceled. Then for both the MRs we will have a canceled status of the pipeline.

Overall pipeline status
Screenshot from 2019-07-18 12-41-12

MR-20
Screenshot from 2019-07-18 12-46-10

MR-21
Screenshot from 2019-07-18 12-45-57

For both MRs, we receive the status of the other MR which is incorrect. And that is the reason I implemented a common name like mr, tag, branch.

**Pull request merged**
