### PR TITLE
Log warnings for caught GitLabApiExceptions

### PR DESCRIPTION
**Pull request by stuartrowe**

### CODE REVIEW

**Comment by casz** [comment]
CI failure
```
[ERROR] /home/travis/build/jenkinsci/gitlab-branch-source-plugin/src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMNavigator.java:[304,19] cannot find symbol
  symbol:   method log(java.util.logging.Level,java.lang.String,org.gitlab4j.api.GitLabApiException)
  location: variable LOGGER of type org.slf4j.Logger
[ERROR] /home/travis/build/jenkinsci/gitlab-branch-source-plugin/src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java:[223,19] cannot find symbol
  symbol:   method log(java.util.logging.Level,java.lang.String,org.gitlab4j.api.GitLabApiException)
  location: variable LOGGER of type org.slf4j.Logger
[ERROR] /home/travis/build/jenkinsci/gitlab-branch-source-plugin/src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java:[303,19] cannot find symbol
  symbol:   method log(java.util.logging.Level,java.lang.String,org.gitlab4j.api.GitLabApiException)
  location: variable LOGGER of type org.slf4j.Logger
[ERROR] /home/travis/build/jenkinsci/gitlab-branch-source-plugin/src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java:[538,19] cannot find symbol
  symbol:   method log(java.util.logging.Level,java.lang.String,org.gitlab4j.api.GitLabApiException)
  location: variable LOGGER of type org.slf4j.Logger
[ERROR] /home/travis/build/jenkinsci/gitlab-branch-source-plugin/src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java:[872,23] cannot find symbol
  symbol:   method log(java.util.logging.Level,java.lang.String,org.gitlab4j.api.GitLabApiException)
  location: variable LOGGER of type org.slf4j.Logger
```

**Comment by stuartrowe** [comment]
Reopening to trigger CI again.

**Comment by stuartrowe** [comment]
https://ci.jenkins.io is struggling...

**Comment by casz** [comment]
ya ci.jenkins.io been struggling for a while 😓

**Comment by stuartrowe** [comment]
Trying one more time.

**Comment by stuartrowe** [comment]
Rebuilding PR

**Pull request merged**
