### PR TITLE
Add support for StringCredentials in credentials configuration

### LINKED ISSUE #107: Please support the "GitLab API Token" credential from GitLab Plugin
This plugin introduces "GitLab Personal Access Token", which appears to serve the same purpose as the ["GitLab API Token"](https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/connection/GitLabApiToken.java) from the GitLab Plugin.

It'd be nice if this plugin could consume GitLab API Tokens where it consumes GitLab Personal Access Token, to save duplication of credential entries.

And if it can't do that in the GitLab Server case, then it'd be nice if the "Convert login and password to token" feature also supported "Convert GitLab API Token to token", and even "Convert Secret Text to token", since it turns out our local Jenkins has API tokens for GitLab in the "Secret text" type too.

### PR DESCRIPTION
**Pull request by ljackiewicz**
Currently, the only type of credentials supported by the plugin for configure credentials is **Personal Access Token**. The proposed changes make it possible to use any type of **StringCredentials** type credentials, such as **Secret text** provided by Plain Credentials plugin or **Vault Secret Text Credential** provided by HashiCorp Vault plugin.

I manually tested the plugin's basic functionalities with configured new type credentials, but as I'm just starting to use this plugin, I don't know if there are any edge cases that would be worth checking further.

To be more precise about the tests, I have tested the following:
- **Test connection** in GitLab Server configuration form
- I created an example **Organization Folder** item configured to retrieve projects from a specific GitLab group. **Scan GitLab Group Log** logged the creation of **Multibranch Pipelines** for projects containing Jenkinsfile and configuring a webhook for them (as I marked **Manage Web Hooks** option in the GitLab Server configuration form). After committing sample changes to the project, the pipeline of a specific branch was triggered

I also made a small change to the "Credentials" help window in the GitLab Server configuration form to indicate the possibility to use other credentials type.

This PR can partly resolve #107, because [GitLab plugin](https://plugins.jenkins.io/gitlab-plugin/) also supports **StringCredentials** type credentials, so it will be possible to use one credential configured for both plugins.

### CODE REVIEW

**Comment by Reamer** [comment]
I am very interested in this function. When will there be a review?

**Comment by jetersen** [comment]
Can you please resolve the merge conflict?

**Comment by ljackiewicz** [comment]
Merge conflicts resolved.

**Review by jetersen — APPROVED** [review]

**Comment by jetersen** [comment]
Much appreciated and for your contribution ☺️

**Pull request merged**
