### PR TITLE
fix potential null pointer in lightweight checkout and support fetching Jenkinsfile from directory

### PR DESCRIPTION
**Pull request by casz**
As project can be nullable due to it's transient nature it is safer to use `projectPath`

I also updated `lastModified` to use the commit date for the `SCMFileSystem`

### CODE REVIEW

**Comment by casz** [comment]
@stephenc Would you mind taking a look :)

I might be able to throw a similar PR over to https://github.com/jenkinsci/gitea-plugin/blob/master/src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMFile.java :)

**Comment by casz** [comment]
The gitlab API does not offer a whole lot of file typing like GitHub API does

This is what GitLab file options provide

https://gitlab.com/api/v4/projects/13555154/repository/tree?ref=folder
https://gitlab.com/api/v4/projects/13555154/repository/files/Jenkinsfile?ref=folder

See API docs here:
https://docs.gitlab.com/ee/api/repositories.html#list-repository-tree
https://docs.gitlab.com/ee/api/repository_files.html#get-file-from-repository

**Comment by baymac** [comment]
Thanks @casz for fixing this. LGTM.

**Comment by casz** [comment]
needs testing as lightweight checkout still fails for merge requests.

**Comment by baymac** [comment]
@jetersen Light checkout doesn't work as expected for MRs. https://issues.jenkins-ci.org/browse/JENKINS-62343?focusedCommentId=390912&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-390912 Could you fix it or point in the direction to fix it?

**Comment by baymac** [comment]
@jetersen Pinging again to get updates on this. FYI light weight checkout works in bitbucket branch source and not in gitlab branch source.

**Pull request merged**
