### PR TITLE
[JENKINS-58361, 57760] Feature/web hook

### PR DESCRIPTION
**Pull request by baymac**
## Fixes:
* Webhooks creation on GitLab Server for Navigator and Source.

https://user-images.githubusercontent.com/23079344/61171176-8fa05080-a591-11e9-91af-3beb13519ed0.png

## Issue:
* Unable to listen to post request on Jenkins instance. Any idea how to implement this?

* GitLab API doesn't support webhooks creation on a group. Although Group webhooks are available in Enterprise Edition but cannot take advantage of it. Currently it is a WIP in GitLab. So for Navigator, individually setting webhooks on all projects.

### CODE REVIEW

**Comment by casz** [comment]
@baymac here is how gitea have implemented the webhook handler in Jenkins: https://github.com/jenkinsci/gitea-plugin/blob/master/src/main/java/org/jenkinsci/plugin/gitea/GiteaWebhookHandler.java

**Comment by baymac** [comment]
Jenkins receives the POST request from GitLab Server.
Screenshot from 2019-07-19 13-47-16
Screenshot from 2019-07-19 13-49-53

I am using `CrumbExclusion` to process the request, so I think the requests are CSRF resistant. Although I am not sure how it works, can someone confirm if it is correct implementation?

**Comment by baymac** [comment]
Requesting review from @jenkinsci/gsoc2019-gitlab-multibranch-pipeline

**Comment by baymac** [comment]
Is it okay to instantiate `WebhookManager` and add `WebhookListener` inside `doPost` method? Or should I do it inside a constructor?

**Comment by markyjackson-taulia** [comment]
> Is it okay to instantiate `WebhookManager` and add `WebhookListener` inside `doPost` method? Or should I do it inside a constructor?
> 
> https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/6d5a9d935a1bd0b2970b8bcc0a44be2cff773f4f/src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabWebhookAction.java#L66

To my knowledge that is ok

**Comment by baymac** [comment]
Implemented Event for Merge Request but not functioning properly. :sweat_smile:

**Comment by baymac** [comment]
Current issue with firing of `SCMHeadEvent` is being tracked here - [JENKINS-58593](https://issues.jenkins-ci.org/browse/JENKINS-58593).

**Pull request merged**
