### PR TITLE
Adds an option to change not just a part but the full build status name.

### PR DESCRIPTION
**Pull request by irrandon**
Adds an option to change not just a part but the full build status name.

Resolves: #176
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by TBBle — APPROVED** [review]

**Comment by jetersen** [comment]
This does not solve it entirely it is missing environment expansion as noted in #176

**Comment by TBBle** [comment]
I agree that environment expansion is valuable, but it wasn't part of [JENKINS-65367](https://issues.jenkins.io/browse/JENKINS-65367), and lack of it shouldn't hold this PR back, as the existing build-name customisation this is improving doesn't have it either.

**Comment by jetersen** [comment]
Well since this allows for customization most users would expect variable expansion to work since it is a common feature for plugins that allow customization in Jenkins.

**Comment by TBBle** [comment]
True, but that's not what [JENKINS-65367](https://issues.jenkins.io/browse/JENKINS-65367) was requesting, so there's no reason to consider that this doesn't solve it just because it doesn't do some other valuable thing. It's not like we're going _backwards_ by merging this as-is.

**Comment by sll552** [comment]
Is there currently anything that prevents merging this?

**Review by jetersen — CHANGES_REQUESTED** [review]
Please implement variable expansion

**Comment by TBBle** [comment]
Since we haven't heard from the PR author in months, I expect that requiring the extra feature of variable expansion (which did not AFAIK already exist in the setting this is expanding upon) just means that this PR will never be "completed" unless someone else steps up to recreate it (or continue it, but copyright status and CLAs can be fraught in such cases).

**Comment by jetersen** [comment]
> but copyright status and CLAs can be fraught in such cases

MIT license and no CLAs are here.

**Comment by TBBle** [comment]
> Because no customization was possible previously, since your adding customization you need to add variable expansion.

Customisation _was_ previously possible, but only for the middle stanza. The comment that introduced env-var expansion into the discussion didn't depend on this change at all, it was asking about the _existing_ customisation feature having env-var expansion. The two feature requests are orthogonal in that regard.

Unless your idea is that env-var expansion should _only_ apply to the new "override" mode, not the existing "customise" mode? If so, that wasn't clear to me at all (since that wasn't the original request).

**Comment by irrandon** [comment]
As I am not really familiar with Jenkins plugin development and just to make sure we are talking about the same thing. You mean variable expansion as in https://www.jenkins.io/doc/developer/plugin-development/pipeline-integration/#variable-substitutions

If you have any example in mind I would appreciate that too.

**Comment by jetersen** [comment]
@irrandon on `job` or `run` you should have access to `getEnvironment` so you could gain access to `EnvVars` which has a `expand` method.

**Comment by jetersen** [comment]
fixed in #257

**Pull request closed without merging**
