### PR TITLE
[JENKINS-58535] Reduce API calls in retrieveActions

### PR DESCRIPTION
**Pull request by casz**
Reduces API calls and simplify web/avatar URL business :+1:

### CODE REVIEW

**Comment by baymac** [comment]
@casz Thanks a lot for cleaning up the code. I knew I had made a mess there. :sweat_smile:

**Comment by casz** [comment]
Think we can remove the todo as that is apparently the intended behavior, I'll look at the exception handling once again 😅

**Comment by casz** [comment]
I added some more exception handling 😅 @baymac

**Comment by baymac** [comment]
@casz okay. :+1:

**Pull request merged**
